### PR TITLE
Add requireFresh to support hot-reloading

### PR DESCRIPTION
**Pull request by AlesJiranek**

### CODE REVIEW

**Comment by epegzz** [comment]
Hey :) Thanks for the pull request, good idea!

But I'd prefer adding the code directly instead of adding it as npm dependency:

```js
const path = require('path');
…
const resolvedFilePath = path.resolve(filePath);
delete require.cache[resolvedFilePath]
Object.assign(vars, require(resolvedFilePath));
```

**Comment by AlesJiranek** [comment]
I was thinking about this option too, but It looked more clear to me to add it as dependency. But as you wish :)

**Comment by epegzz** [comment]
Maybe adding a comment will add clearity :)

**Comment by epegzz** [comment]
Now implemented :)

**Pull request closed without merging**
